### ISSUE TITLE
cannot run the download.py

### ISSUE THREAD

**Issue by aareman** [tomahim/py-image-dataset-generator#11]
**running: python3 download.py "red car" gives:**

ge_downloader.py", line 5, in <module>
    from typing import NoReturn, Tuple
ImportError: cannot import name 'NoReturn'

**Also the unittest fails:**

python3 -m unittest discover

E
======================================================================
ERROR: tests.image_grabber.test_image_downloader (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.image_grabber.test_image_downloader
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/??????/py-image-dataset-generator/tests/image_grabber/test_image_downloader.py", line 6, in <module>
    from image_grabber.image_downloader import ImageDownloader
  File "/home/??????/py-image-dataset-generator/image_grabber/image_downloader.py", line 5, in <module>
    from typing import NoReturn, Tuple
ImportError: cannot import name 'NoReturn'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)

**Comment by tomahim** [comment]
I see you use python 3.5, for now the python 3.6.4 is needed to make it work. 
The `NoReturn` type hint is not supported before this version.
