### ISSUE TITLE
DevToolsActivePort file doesn't exist

### ISSUE THREAD

**Issue by ayomide101** [tomahim/py-image-dataset-generator#12]
I tried running the download.py but it threw up some errors

`
python download.py "red car" -limit=150 -dest=cars -resize=250x250
> searching image on Google : https://www.google.co.in/search?q=red+car&source=lnms&tbm=isch
Traceback (most recent call last):
  File "download.py", line 88, in <module>
    downloader.download_images(keyword)
  File "/root/training/py-image-dataset-generator/image_grabber/image_downloader.py", line 49, in download_images
    images.extend(google_grabber.get_images_url(self.keyword, self.limit))
  File "/root/training/py-image-dataset-generator/image_grabber/google_grabber.py", line 31, in get_images_url
    browser = webdriver.Chrome(chrome_options=options)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
  (Driver info: chromedriver=2.39.562737 (dba483cee6a5f15e2e2d73df16968ab10b38a2bf),platform=Linux 3.10.0-862.2.3.el7.x86_64 x86_64)
`

**Comment by tomahim** [comment]
Hi,

It's seems that chromedriver is not well installed. I put some instructions on the readme file for these kind problems. Please check this and let me know.
