### ISSUE TITLE
Unable to run image-dataset-generator

### ISSUE THREAD

**Issue by SelviPrakash** [tomahim/py-image-dataset-generator#18]
Getting error when I try to ran this command **python download.py "red car" -limit=150 -dest=folder_name -resize=250x250**
Note: I ran it in Jupyterlab
Log:
```
Traceback (most recent call last):

  File "download.py", line 2, in <module>

    from image_grabber import image_downloader

  File "/home/jovyan/py-image-dataset-generator/image_grabber/image_downloader.py", line 7, in <module>

    from skimage import io as _io

  File "/srv/conda/envs/py36-test/lib/python3.6/site-packages/skimage/__init__.py", line 158, in <module>

    from .util.dtype import *

  File "/srv/conda/envs/py36-test/lib/python3.6/site-packages/skimage/util/__init__.py", line 7, in <module>

    from .arraycrop import crop

  File "/srv/conda/envs/py36-test/lib/python3.6/site-packages/skimage/util/arraycrop.py", line 8, in <module>

    from numpy.lib.arraypad import _validate_lengths

ImportError: cannot import name '_validate_lengths'
```

**Comment by RoHei** [comment]
Same error for me, when running code under Manjaro Linux. My debugging turned out, that the following line from the google_grabber.py  creates an empty result - but it shouldn`t:

`images = browser.find_elements_by_class_name("rg_meta")`
