### ISSUE TITLE
Import Error for validate_lengths

### ISSUE THREAD

**Issue by dasmehdix** [tomahim/py-image-dataset-generator#21]
Hi all. I have installed all libraries correctly. When I tried to run "unittest" this error occured.

`ImportError: Failed to import test module: tests.image_grabber.test_image_downloader
Traceback (most recent call last):
  File "C:\Users\Eriklab2\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Eriklab2\AppData\Local\Programs\Python\Python37\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\Users\Eriklab2\Desktop\repoboy\py-image-dataset-generator\tests\image_grabber\test_image_downloader.py", line 6, in <module>
    from image_grabber.image_downloader import ImageDownloader
  File "C:\Users\Eriklab2\Desktop\repoboy\py-image-dataset-generator\image_grabber\image_downloader.py", line 7, in <module>
    from skimage import io as _io
  File "C:\Users\Eriklab2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\__init__.py", line 158, in <module>
    from .util.dtype import *
  File "C:\Users\Eriklab2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\util\__init__.py", line 7, in <module>
    from .arraycrop import crop
  File "C:\Users\Eriklab2\AppData\Local\Programs\Python\Python37\lib\site-packages\skimage\util\arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' `

**Comment by EduardoRonchi** [comment]
I have the same error
