### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by bodhwani** [tomahim/py-image-dataset-generator#9]
folder_path: str, 
Not accepting argument as a string in case of -folder=folder_name

**Comment by tomahim** [comment]
Hi,

Can you be more specific? What is file line with the syntax error and the command line you are using ? Also what's your Python version ? 

Thank you

**Comment by HuguesBadzou** [comment]
You need to have python 3.6.4 or more except 3.7 because it doesn't works actually with this version. I downgraded my version to 3.6.5 and it worked. I used this command line: python3 augmentation.py -folder=your_folder_path -limit=50

**Comment by metebyte** [comment]
I don't know if it's the same error depending on **arguments**, but didn't want to open a new issue which will be **titled as same as this issue**. When I run this command
```bash
python download.py "funny cats" -limit=100 -dest=images -resize=250x250
```
It raises
```bash
Traceback (most recent call last):
  File "download.py", line 2, in <module>
    from image_grabber import image_downloader
  File "/Users/metebyte/Documents/GitHub/py-image-dataset-generator/image_grabber/image_downloader.py", line 34
    def download_images(self, keyword: str) -> NoReturn:
                                     ^
SyntaxError: invalid syntax
```
Also got some errors while installing `pip` required dependencies which was `chromedriver` so manually installed it.

**Comment by alexlaurence** [comment]
make sure you have scipy installed

`pip install scipy`

and make sure you are in python 3.

`python3.7 augmentation.py -folder=my_folder_path -limit=1000`
